<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>Lieutenant</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>x86;x64;ARM64</Platforms>
    <RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
    <UseWinUI>true</UseWinUI>
    <WinUISDKReferences>false</WinUISDKReferences>
	<WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
    <Nullable>enable</Nullable>
	<JsonSerializerIsReflectionEnabledByDefault>true</JsonSerializerIsReflectionEnabledByDefault>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="AppDesign\ArduinoElements\**" />
    <Content Remove="AppDesign\ArduinoElements\**" />
    <EmbeddedResource Remove="AppDesign\ArduinoElements\**" />
    <None Remove="AppDesign\ArduinoElements\**" />
    <Page Remove="AppDesign\ArduinoElements\**" />
    <PRIResource Remove="AppDesign\ArduinoElements\**" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="API\AppJsonContext.cs" />
    <Compile Remove="API\BootCampExtractor.cs" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="CustomStyles\CustomButtons.xaml" />
    <None Remove="CustomStyles\CustomTextBlocks.xaml" />
    <None Remove="Pages\DownloadBootcamp.xaml" />
    <None Remove="Pages\DownloadProgress.xaml" />
    <None Remove="Pages\HomePage.xaml" />
    <None Remove="Pages\Settings.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Manifest Include="$(ApplicationManifest)" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.28000.2705" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="2.5.1" />
    <PackageReference Include="SevenZipExtractor" Version="1.0.19" />
    <PackageReference Include="SharpZipLib" Version="1.4.2" />
    <PackageReference Include="System.Management" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <None Update="API\BootcampLinks.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <Page Update="Pages\DownloadProgress.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>

  <ItemGroup>
    <Page Update="Pages\DownloadBootcamp.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>

  <ItemGroup>
    <Page Update="CustomStyles\CustomButtons.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>

  <ItemGroup>
    <Page Update="CustomStyles\CustomTextBlocks.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>

  <ItemGroup>
    <Page Update="Pages\HomePage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>

  <ItemGroup>
    <Page Update="Pages\Settings.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>

    <!-- Publish Properties -->
  <PropertyGroup>
    <PublishReadyToRun Condition="'$(Configuration)' == 'Debug'">False</PublishReadyToRun>
    <PublishReadyToRun Condition="'$(Configuration)' != 'Debug'">True</PublishReadyToRun>
    <PublishTrimmed Condition="'$(Configuration)' == 'Debug'">False</PublishTrimmed>
    <PublishTrimmed Condition="'$(Configuration)' != 'Debug'">True</PublishTrimmed>
  </PropertyGroup>
</Project>